from app.exceptions.app_exception import AppException


class RuntimeException(AppException):
    pass